version: '3.7'

services:
  stack-task-ui:
    container_name: stack-task-ui
    image: srilakshmi29/stack-task-ui
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true